// <auto-generated />
using System;
using BIMConcierge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BIMConcierge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BIMConcierge.Api.Entities.AchievementEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = "ach-first-login",
                            Description = "Fez login pela primeira vez no BIM Concierge",
                            Icon = "Star",
                            Title = "Primeiro Acesso",
                            XpReward = 50
                        },
                        new
                        {
                            Id = "ach-first-tutorial",
                            Description = "Completou o primeiro tutorial",
                            Icon = "School",
                            Title = "Aprendiz",
                            XpReward = 100
                        },
                        new
                        {
                            Id = "ach-five-tutorials",
                            Description = "Completou 5 tutoriais",
                            Icon = "Trophy",
                            Title = "Estudante Dedicado",
                            XpReward = 250
                        },
                        new
                        {
                            Id = "ach-perfect-score",
                            Description = "Obteve 100% em um tutorial",
                            Icon = "CheckCircle",
                            Title = "Nota Máxima",
                            XpReward = 150
                        },
                        new
                        {
                            Id = "ach-standards-master",
                            Description = "Corrigiu 10 violações de padrão da empresa",
                            Icon = "Shield",
                            Title = "Guardião dos Padrões",
                            XpReward = 200
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = "company-demo-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "BIM Concierge Demo"
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.CompanyStandardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoFix")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyStandards");

                    b.HasData(
                        new
                        {
                            Id = "std-naming-001",
                            AlertLevel = 2,
                            AutoFix = false,
                            Category = "Nomenclatura",
                            CompanyId = "company-demo-001",
                            Description = "Views devem seguir o padrão DISCIPLINA-TIPO-PAVIMENTO",
                            IsActive = true,
                            Name = "Nome de Views",
                            Rule = "ViewNameRegex:^[A-Z]{3}-[A-Z]{3}-.*$"
                        },
                        new
                        {
                            Id = "std-naming-002",
                            AlertLevel = 2,
                            AutoFix = false,
                            Category = "Nomenclatura",
                            CompanyId = "company-demo-001",
                            Description = "Sheets devem ter número no formato XX.XX",
                            IsActive = true,
                            Name = "Nome de Sheets",
                            Rule = "SheetNumberRegex:^\\d{2}\\.\\d{2}$"
                        },
                        new
                        {
                            Id = "std-model-001",
                            AlertLevel = 1,
                            AutoFix = true,
                            Category = "Modelagem",
                            CompanyId = "company-demo-001",
                            Description = "Paredes de detalhe não devem ser Room Bounding",
                            IsActive = true,
                            Name = "Paredes sem Room Bounding",
                            Rule = "WallRoomBounding:DetailWalls=false"
                        },
                        new
                        {
                            Id = "std-model-002",
                            AlertLevel = 1,
                            AutoFix = false,
                            Category = "Modelagem",
                            CompanyId = "company-demo-001",
                            Description = "Paredes devem estar conectadas a um nível superior",
                            IsActive = true,
                            Name = "Altura de paredes",
                            Rule = "WallTopConstraint:NotUnconnected"
                        },
                        new
                        {
                            Id = "std-doc-001",
                            AlertLevel = 0,
                            AutoFix = false,
                            Category = "Documentação",
                            CompanyId = "company-demo-001",
                            Description = "Vistas de planta devem usar escala 1:50 ou 1:100",
                            IsActive = true,
                            Name = "Escala de vistas",
                            Rule = "ViewScale:FloorPlan=50,100"
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.LicenseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsedSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Licenses");

                    b.HasData(
                        new
                        {
                            Id = "license-ent-001",
                            CompanyId = "company-demo-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Key = "BIM-DEMO-0001-0001",
                            MaxSeats = 999,
                            Type = "Enterprise",
                            UsedSeats = 0
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.ProgressEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer");

                    b.Property<string>("TutorialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.HasIndex("UserId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.TutorialEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMins")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompanyOwned")
                        .HasColumnType("boolean");

                    b.Property<int>("StepCount")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tutorials");

                    b.HasData(
                        new
                        {
                            Id = "tut-walls-001",
                            Category = "Modelagem",
                            Description = "Aprenda a criar e configurar paredes no Revit, incluindo tipos, alturas e conexões.",
                            Difficulty = "Beginner",
                            DurationMins = 15,
                            IsCompanyOwned = false,
                            StepCount = 5,
                            ThumbnailUrl = "",
                            Title = "Criando Paredes no Revit"
                        },
                        new
                        {
                            Id = "tut-floors-001",
                            Category = "Modelagem",
                            Description = "Tutorial completo sobre criação de pisos e lajes estruturais.",
                            Difficulty = "Intermediate",
                            DurationMins = 20,
                            IsCompanyOwned = false,
                            StepCount = 6,
                            ThumbnailUrl = "",
                            Title = "Pisos e Lajes"
                        },
                        new
                        {
                            Id = "tut-sheets-001",
                            Category = "Documentação",
                            Description = "Como gerar pranchas de impressão com carimbo e vistas organizadas.",
                            Difficulty = "Intermediate",
                            DurationMins = 25,
                            IsCompanyOwned = false,
                            StepCount = 7,
                            ThumbnailUrl = "",
                            Title = "Gerando Pranchas"
                        },
                        new
                        {
                            Id = "tut-families-001",
                            Category = "Famílias",
                            Description = "Criação de famílias com parâmetros condicionais e fórmulas.",
                            Difficulty = "Advanced",
                            DurationMins = 40,
                            IsCompanyOwned = false,
                            StepCount = 10,
                            ThumbnailUrl = "",
                            Title = "Famílias Paramétricas"
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.TutorialStepEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AutoApplicable")
                        .HasColumnType("boolean");

                    b.Property<string>("HighlightZone")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RevitCommand")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TutorialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationRule")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialSteps");

                    b.HasData(
                        new
                        {
                            Id = "step-w1",
                            AutoApplicable = false,
                            HighlightZone = "Ribbon.Architecture.Build",
                            Instruction = "Clique em Architecture > Wall > Wall: Architectural",
                            Order = 1,
                            RevitCommand = "ID_OBJECTS_WALL",
                            Title = "Abrir ferramenta Wall",
                            TutorialId = "tut-walls-001"
                        },
                        new
                        {
                            Id = "step-w2",
                            AutoApplicable = false,
                            HighlightZone = "Properties.TypeSelector",
                            Instruction = "No Type Selector, escolha 'Basic Wall: Generic - 200mm'",
                            Order = 2,
                            Title = "Selecionar tipo",
                            TutorialId = "tut-walls-001"
                        },
                        new
                        {
                            Id = "step-w3",
                            AutoApplicable = false,
                            HighlightZone = "Properties.UnconnectedHeight",
                            Instruction = "No painel Properties, ajuste 'Unconnected Height' para 3000mm",
                            Order = 3,
                            Title = "Definir altura",
                            TutorialId = "tut-walls-001"
                        },
                        new
                        {
                            Id = "step-w4",
                            AutoApplicable = false,
                            HighlightZone = "Canvas",
                            Instruction = "Clique dois pontos na vista de planta para criar a parede",
                            Order = 4,
                            Title = "Desenhar parede",
                            TutorialId = "tut-walls-001"
                        },
                        new
                        {
                            Id = "step-w5",
                            AutoApplicable = false,
                            HighlightZone = "Ribbon.Modify",
                            Instruction = "Pressione ESC ou clique em Modify para finalizar o comando",
                            Order = 5,
                            RevitCommand = "ID_OBJECTS_MODIFY",
                            Title = "Finalizar",
                            TutorialId = "tut-walls-001"
                        },
                        new
                        {
                            Id = "step-f1",
                            AutoApplicable = false,
                            HighlightZone = "Ribbon.Architecture.Build",
                            Instruction = "Clique em Architecture > Floor > Floor: Architectural",
                            Order = 1,
                            RevitCommand = "ID_OBJECTS_FLOOR",
                            Title = "Abrir ferramenta Floor",
                            TutorialId = "tut-floors-001"
                        },
                        new
                        {
                            Id = "step-f2",
                            AutoApplicable = false,
                            HighlightZone = "Ribbon.Modify.Draw",
                            Instruction = "Use Pick Walls para selecionar as paredes como contorno do piso",
                            Order = 2,
                            Title = "Selecionar contorno",
                            TutorialId = "tut-floors-001"
                        },
                        new
                        {
                            Id = "step-f3",
                            AutoApplicable = false,
                            HighlightZone = "OptionsBar.Offset",
                            Instruction = "Verifique se o offset está em -200mm para que o piso fique alinhado",
                            Order = 3,
                            Title = "Ajustar offset",
                            TutorialId = "tut-floors-001"
                        },
                        new
                        {
                            Id = "step-f4",
                            AutoApplicable = false,
                            HighlightZone = "Ribbon.Modify.Mode",
                            Instruction = "Clique no botão verde (Finish Edit Mode) para criar o piso",
                            Order = 4,
                            Title = "Confirmar edição",
                            TutorialId = "tut-floors-001"
                        },
                        new
                        {
                            Id = "step-f5",
                            AutoApplicable = false,
                            HighlightZone = "QuickAccess.3D",
                            Instruction = "Abra a vista 3D (atalho: 3D) para verificar o resultado",
                            Order = 5,
                            RevitCommand = "ID_VIEW_DEFAULT_3DVIEW",
                            Title = "Verificar 3D",
                            TutorialId = "tut-floors-001"
                        },
                        new
                        {
                            Id = "step-f6",
                            AutoApplicable = false,
                            HighlightZone = "Properties.TypeSelector",
                            Instruction = "Se necessário, altere o tipo do piso no painel Properties",
                            Order = 6,
                            Title = "Ajustar tipo",
                            TutorialId = "tut-floors-001"
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.UserAchievement", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AchievementId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user-admin-001",
                            AvatarUrl = "",
                            CompanyId = "company-demo-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bimconcierge.com",
                            Level = 1,
                            Name = "Admin Demo",
                            PasswordHash = "$2a$11$arY.DKm7gaMSUkZqbI2lPunv4scXIOuhpzmLTPGm3SsWfHGeK9yc2",
                            Role = "Admin",
                            XpPoints = 0
                        });
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.CompanyStandardEntity", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.Company", "Company")
                        .WithMany("Standards")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.LicenseEntity", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.Company", "Company")
                        .WithMany("Licenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.ProgressEntity", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.TutorialEntity", "Tutorial")
                        .WithMany()
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIMConcierge.Api.Entities.UserEntity", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutorial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.TutorialStepEntity", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.TutorialEntity", "Tutorial")
                        .WithMany("Steps")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutorial");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.UserAchievement", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.AchievementEntity", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIMConcierge.Api.Entities.UserEntity", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.UserEntity", b =>
                {
                    b.HasOne("BIMConcierge.Api.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.AchievementEntity", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.Company", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Standards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.TutorialEntity", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BIMConcierge.Api.Entities.UserEntity", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
