//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMConcierge.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMConcierge.UI.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conquistas.
        /// </summary>
        public static string AchievementsHeading {
            get {
                return ResourceManager.GetString("AchievementsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar conquistas: {0}.
        /// </summary>
        public static string AchievementsLoadError {
            get {
                return ResourceManager.GetString("AchievementsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acompanhe seu progresso e desbloqueie recompensas..
        /// </summary>
        public static string AchievementsSubtitle {
            get {
                return ResourceManager.GetString("AchievementsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Conquistas.
        /// </summary>
        public static string AchievementsTitle {
            get {
                return ResourceManager.GetString("AchievementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquiteto.
        /// </summary>
        public static string Architect {
            get {
                return ResourceManager.GetString("Architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais inválidas..
        /// </summary>
        public static string AuthInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chave de licença inválida..
        /// </summary>
        public static string AuthInvalidLicenseKey {
            get {
                return ResourceManager.GetString("AuthInvalidLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Licença expirada. Contate o administrador..
        /// </summary>
        public static string AuthLicenseExpired {
            get {
                return ResourceManager.GetString("AuthLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Licença expirada. Conecte-se à internet para renovar..
        /// </summary>
        public static string AuthLicenseExpiredRenew {
            get {
                return ResourceManager.GetString("AuthLicenseExpiredRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem conexão e nenhuma licença em cache..
        /// </summary>
        public static string AuthNoConnectionNoLicense {
            get {
                return ResourceManager.GetString("AuthNoConnectionNoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem conexão e nenhum usuário em cache..
        /// </summary>
        public static string AuthNoConnectionNoUser {
            get {
                return ResourceManager.GetString("AuthNoConnectionNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modo offline — dados em cache..
        /// </summary>
        public static string AuthOfflineMode {
            get {
                return ResourceManager.GetString("AuthOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limite de seats atingido. Contate o administrador..
        /// </summary>
        public static string AuthSeatLimitReached {
            get {
                return ResourceManager.GetString("AuthSeatLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativas: .
        /// </summary>
        public static string CorrectionsActive {
            get {
                return ResourceManager.GetString("CorrectionsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correções Automáticas.
        /// </summary>
        public static string CorrectionsAutoFix {
            get {
                return ResourceManager.GetString("CorrectionsAutoFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrigir violações triviais automaticamente.
        /// </summary>
        public static string CorrectionsAutoFixDesc {
            get {
                return ResourceManager.GetString("CorrectionsAutoFixDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrigidas: .
        /// </summary>
        public static string CorrectionsCorrected {
            get {
                return ResourceManager.GetString("CorrectionsCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ignorar.
        /// </summary>
        public static string CorrectionsDismiss {
            get {
                return ResourceManager.GetString("CorrectionsDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elemento: .
        /// </summary>
        public static string CorrectionsElement {
            get {
                return ResourceManager.GetString("CorrectionsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O modelo está em conformidade com os padrões da empresa..
        /// </summary>
        public static string CorrectionsEmptyDesc {
            get {
                return ResourceManager.GetString("CorrectionsEmptyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma violação encontrada.
        /// </summary>
        public static string CorrectionsEmptyTitle {
            get {
                return ResourceManager.GetString("CorrectionsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todos.
        /// </summary>
        public static string CorrectionsFilterAll {
            get {
                return ResourceManager.GetString("CorrectionsFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string CorrectionsFilterError {
            get {
                return ResourceManager.GetString("CorrectionsFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Info.
        /// </summary>
        public static string CorrectionsFilterInfo {
            get {
                return ResourceManager.GetString("CorrectionsFilterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso.
        /// </summary>
        public static string CorrectionsFilterWarning {
            get {
                return ResourceManager.GetString("CorrectionsFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao corrigir: {0}.
        /// </summary>
        public static string CorrectionsFixError {
            get {
                return ResourceManager.GetString("CorrectionsFixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção em Tempo Real.
        /// </summary>
        public static string CorrectionsHeading {
            get {
                return ResourceManager.GetString("CorrectionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar correções: {0}.
        /// </summary>
        public static string CorrectionsLoadError {
            get {
                return ResourceManager.GetString("CorrectionsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando correções....
        /// </summary>
        public static string CorrectionsLoading {
            get {
                return ResourceManager.GetString("CorrectionsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Monitoramento em tempo real ativo..
        /// </summary>
        public static string CorrectionsMonitoringActive {
            get {
                return ResourceManager.GetString("CorrectionsMonitoringActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Monitore e corrija violações de padrões BIM detectadas automaticamente no modelo..
        /// </summary>
        public static string CorrectionsSubtitle {
            get {
                return ResourceManager.GetString("CorrectionsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STATUS DO SISTEMA.
        /// </summary>
        public static string CorrectionsSystemStatus {
            get {
                return ResourceManager.GetString("CorrectionsSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Correção em Tempo Real.
        /// </summary>
        public static string CorrectionsTitle {
            get {
                return ResourceManager.GetString("CorrectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a REGRA VIOLADA.
        /// </summary>
        public static string CorrectionsViolatedRule {
            get {
                return ResourceManager.GetString("CorrectionsViolatedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}% Concluído.
        /// </summary>
        public static string DashboardCompleted {
            get {
                return ResourceManager.GetString("DashboardCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrigiu elementos sobrepostos.
        /// </summary>
        public static string DashboardFixedOverlapping {
            get {
                return ResourceManager.GetString("DashboardFixedOverlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ITENS MODELADOS.
        /// </summary>
        public static string DashboardItemsModeled {
            get {
                return ResourceManager.GetString("DashboardItemsModeled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modelou Parede Básica.
        /// </summary>
        public static string DashboardModeledBasicWall {
            get {
                return ResourceManager.GetString("DashboardModeledBasicWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Convenção de Nomenclatura.
        /// </summary>
        public static string DashboardNamingConvention {
            get {
                return ResourceManager.GetString("DashboardNamingConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua taxa de conformidade para nomenclatura de níveis e vistas estruturais..
        /// </summary>
        public static string DashboardNamingDescription {
            get {
                return ResourceManager.GetString("DashboardNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OPERAÇÕES NO PADRÃO.
        /// </summary>
        public static string DashboardOperationsOnStandard {
            get {
                return ResourceManager.GetString("DashboardOperationsOnStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atividade Recente.
        /// </summary>
        public static string DashboardRecentActivity {
            get {
                return ResourceManager.GetString("DashboardRecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ESTÁVEL.
        /// </summary>
        public static string DashboardStable {
            get {
                return ResourceManager.GetString("DashboardStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão em Foco.
        /// </summary>
        public static string DashboardStandardInFocus {
            get {
                return ResourceManager.GetString("DashboardStandardInFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciou Tutorial: Paredes Cortina.
        /// </summary>
        public static string DashboardStartedTutorial {
            get {
                return ResourceManager.GetString("DashboardStartedTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aqui está o que está acontecendo com seus modelos hoje..
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há 15 min.
        /// </summary>
        public static string DashboardTimeAgo15Min {
            get {
                return ResourceManager.GetString("DashboardTimeAgo15Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há 1 hora.
        /// </summary>
        public static string DashboardTimeAgo1Hour {
            get {
                return ResourceManager.GetString("DashboardTimeAgo1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Há 2 min.
        /// </summary>
        public static string DashboardTimeAgo2Min {
            get {
                return ResourceManager.GetString("DashboardTimeAgo2Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Dashboard.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ver Detalhes.
        /// </summary>
        public static string DashboardViewDetails {
            get {
                return ResourceManager.GetString("DashboardViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AVISOS CORRIGIDOS.
        /// </summary>
        public static string DashboardWarningsCorrected {
            get {
                return ResourceManager.GetString("DashboardWarningsCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo(a) de volta, {0}!.
        /// </summary>
        public static string DashboardWelcome {
            get {
                return ResourceManager.GetString("DashboardWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha todos os campos..
        /// </summary>
        public static string LoginAllFieldsRequired {
            get {
                return ResourceManager.GetString("LoginAllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fale com o suporte.
        /// </summary>
        public static string LoginContactSupport {
            get {
                return ResourceManager.GetString("LoginContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira suas credenciais para acessar sua conta..
        /// </summary>
        public static string LoginCredentials {
            get {
                return ResourceManager.GetString("LoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail Corporativo.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no login..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinamento gamificado integrado.
        /// </summary>
        public static string LoginFeature1 {
            get {
                return ResourceManager.GetString("LoginFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção de modelagem em tempo real.
        /// </summary>
        public static string LoginFeature2 {
            get {
                return ResourceManager.GetString("LoginFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padronização automatizada da empresa.
        /// </summary>
        public static string LoginFeature3 {
            get {
                return ResourceManager.GetString("LoginFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esqueceu a senha?.
        /// </summary>
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo ao assistente inteligente que transforma a maneira como seu escritório projeta no Revit..
        /// </summary>
        public static string LoginHeroSubtitle {
            get {
                return ResourceManager.GetString("LoginHeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua Jornada BIM Começa Aqui.
        /// </summary>
        public static string LoginHeroTitle {
            get {
                return ResourceManager.GetString("LoginHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chave de Licença.
        /// </summary>
        public static string LoginLicenseKey {
            get {
                return ResourceManager.GetString("LoginLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Precisa de ajuda?.
        /// </summary>
        public static string LoginNeedHelp {
            get {
                return ResourceManager.GetString("LoginNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lembrar de mim.
        /// </summary>
        public static string LoginRememberMe {
            get {
                return ResourceManager.GetString("LoginRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo de volta.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conquistas.
        /// </summary>
        public static string NavAchievements {
            get {
                return ResourceManager.GetString("NavAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correções.
        /// </summary>
        public static string NavCorrections {
            get {
                return ResourceManager.GetString("NavCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painel Principal.
        /// </summary>
        public static string NavDashboard {
            get {
                return ResourceManager.GetString("NavDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Progresso do Aluno.
        /// </summary>
        public static string NavProgress {
            get {
                return ResourceManager.GetString("NavProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrões da Empresa.
        /// </summary>
        public static string NavStandards {
            get {
                return ResourceManager.GetString("NavStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tutoriais.
        /// </summary>
        public static string NavTutorials {
            get {
                return ResourceManager.GetString("NavTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Próximo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anterior.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOTA MÉDIA.
        /// </summary>
        public static string ProgressAverageScore {
            get {
                return ResourceManager.GetString("ProgressAverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NÍVEL ATUAL.
        /// </summary>
        public static string ProgressCurrentLevel {
            get {
                return ResourceManager.GetString("ProgressCurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Progresso do Aluno.
        /// </summary>
        public static string ProgressHeading {
            get {
                return ResourceManager.GetString("ProgressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HORAS DE APRENDIZADO.
        /// </summary>
        public static string ProgressHoursLearning {
            get {
                return ResourceManager.GetString("ProgressHoursLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar progresso: {0}.
        /// </summary>
        public static string ProgressLoadError {
            get {
                return ResourceManager.GetString("ProgressLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acompanhe sua evolução nos tutoriais e treinamentos BIM..
        /// </summary>
        public static string ProgressSubtitle {
            get {
                return ResourceManager.GetString("ProgressSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Progresso do Aluno.
        /// </summary>
        public static string ProgressTitle {
            get {
                return ResourceManager.GetString("ProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TUTORIAIS CONCLUÍDOS.
        /// </summary>
        public static string ProgressTutorialsCompleted {
            get {
                return ResourceManager.GetString("ProgressTutorialsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correção automática ativada.
        /// </summary>
        public static string StandardsAutoCorrection {
            get {
                return ResourceManager.GetString("StandardsAutoCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boas Práticas.
        /// </summary>
        public static string StandardsBestPractices {
            get {
                return ResourceManager.GetString("StandardsBestPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrões da Empresa.
        /// </summary>
        public static string StandardsHeading {
            get {
                return ResourceManager.GetString("StandardsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar padrões: {0}.
        /// </summary>
        public static string StandardsLoadError {
            get {
                return ResourceManager.GetString("StandardsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Requisitos de LOD.
        /// </summary>
        public static string StandardsLOD {
            get {
                return ResourceManager.GetString("StandardsLOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Convenções de Nomenclatura.
        /// </summary>
        public static string StandardsNaming {
            get {
                return ResourceManager.GetString("StandardsNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar Alterações.
        /// </summary>
        public static string StandardsSaveChanges {
            get {
                return ResourceManager.GetString("StandardsSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerencie as regras de nomenclatura, LOD e boas práticas do escritório..
        /// </summary>
        public static string StandardsSubtitle {
            get {
                return ResourceManager.GetString("StandardsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Padrões da Empresa.
        /// </summary>
        public static string StandardsTitle {
            get {
                return ResourceManager.GetString("StandardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Regras de Workset.
        /// </summary>
        public static string StandardsWorkset {
            get {
                return ResourceManager.GetString("StandardsWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todos.
        /// </summary>
        public static string TutorialsFilterAll {
            get {
                return ResourceManager.GetString("TutorialsFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquitetura.
        /// </summary>
        public static string TutorialsFilterArchitecture {
            get {
                return ResourceManager.GetString("TutorialsFilterArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrões.
        /// </summary>
        public static string TutorialsFilterStandards {
            get {
                return ResourceManager.GetString("TutorialsFilterStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estrutura.
        /// </summary>
        public static string TutorialsFilterStructure {
            get {
                return ResourceManager.GetString("TutorialsFilterStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biblioteca de Treinamentos.
        /// </summary>
        public static string TutorialsHeading {
            get {
                return ResourceManager.GetString("TutorialsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar tutoriais: {0}.
        /// </summary>
        public static string TutorialsLoadError {
            get {
                return ResourceManager.GetString("TutorialsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando tutoriais....
        /// </summary>
        public static string TutorialsLoading {
            get {
                return ResourceManager.GetString("TutorialsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} min.
        /// </summary>
        public static string TutorialsMinutes {
            get {
                return ResourceManager.GetString("TutorialsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [Preview do Tutorial].
        /// </summary>
        public static string TutorialsPreview {
            get {
                return ResourceManager.GetString("TutorialsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INICIAR TRILHA.
        /// </summary>
        public static string TutorialsStartTrack {
            get {
                return ResourceManager.GetString("TutorialsStartTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} Passos.
        /// </summary>
        public static string TutorialsSteps {
            get {
                return ResourceManager.GetString("TutorialsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aprimore suas habilidades com tutoriais interativos guiados diretamente no Revit..
        /// </summary>
        public static string TutorialsSubtitle {
            get {
                return ResourceManager.GetString("TutorialsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIMConcierge - Biblioteca de Tutoriais.
        /// </summary>
        public static string TutorialsTitle {
            get {
                return ResourceManager.GetString("TutorialsTitle", resourceCulture);
            }
        }
    }
}
